#!/bin/bash
# Convert env.txt to GitHub Secrets format
# Based on your actual .env file

echo "🔐 GitHub Secrets Configuration for Healink CI/CD"
echo "=================================================="
echo ""
echo "Copy these secrets to GitHub:"
echo "https://github.com/oggycat-dev/dot-net-healink-back-end/settings/secrets/actions"
echo ""
echo "=================================================="
echo ""

echo "### 🗄️ DATABASE ###"
echo "DB_USERNAME=admin"
echo "DB_PASSWORD=admin@123"
echo ""

echo "### 🔑 JWT & AUTHENTICATION ###"
echo "JWT_SECRET=HealinkMicroserviceSecretKeyIsLongEnoughToBeUsedWithJWT"
echo "JWT_ISSUER=Healink"
echo "JWT_AUDIENCE=Healink.Users"
echo "JWT_EXPIRES_IN_MINUTES=60"
echo ""

echo "### 🐰 RABBITMQ ###"
echo "RABBITMQ_USERNAME=admin"
echo "RABBITMQ_PASSWORD=admin@123"
echo ""

echo "### 📮 REDIS ###"
echo "REDIS_PASSWORD=admin@123"
echo ""

echo "### 📧 EMAIL (SMTP) ###"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_PORT=587"
echo "SMTP_USERNAME=nguyenhoainamvt99@gmail.com"
echo "SMTP_PASSWORD=ezrn myqu nphw qqnz"
echo ""

echo "### 💳 MOMO PAYMENT GATEWAY ###"
echo "MOMO_PARTNER_CODE=MOMO8UK320250913_TEST"
echo "MOMO_ACCESS_KEY=Tyz9FMyviI6mOYEn"
echo "MOMO_SECRET_KEY=ozTlfYxWaTPr3WrrlSvBvvKNvyc5fqCz"
echo "MOMO_API_ENDPOINT=https://test-payment.momo.vn/v2/gateway/api"
echo ""

echo "### ☁️ AWS S3 ###"
echo "⚠️  WARNING: Old AWS credentials have been EXPOSED!"
echo "⚠️  You MUST create NEW credentials!"
echo "AWS_S3_BUCKET_NAME=healink-upload-file"
echo "AWS_S3_REGION=ap-southeast-2"
echo "AWS_S3_ACCESS_KEY=<CREATE_NEW_KEY>  # ⚠️ Create new Access Key from IAM Console"
echo "AWS_S3_SECRET_KEY=<CREATE_NEW_SECRET>  # ⚠️ Use secret from the new Access Key"
echo ""

echo "### 🔒 SECURITY ###"
echo "PASSWORD_ENCRYPTION_KEY=K9ltF1d2jlYvLsaN6AdmiaPHY8qwqUIW"
echo ""

echo "### 👤 ADMIN ACCOUNT ###"
echo "ADMIN_EMAIL=admin@healink.com"
echo "ADMIN_PASSWORD=admin@123"
echo ""

echo "=================================================="
echo ""
echo "📝 NEXT STEPS:"
echo ""
echo "1. ⚠️  ROTATE AWS CREDENTIALS IMMEDIATELY:"
echo "   - Go to: https://console.aws.amazon.com/iam/home#/security_credentials"
echo "   - Deactivate old key: AKIA4OG4NBUIBJ4MVLM6"
echo "   - Create new Access Key"
echo "   - Update AWS_S3_ACCESS_KEY and AWS_S3_SECRET_KEY"
echo ""
echo "2. Add secrets to GitHub:"
echo "   - Settings → Secrets and variables → Actions"
echo "   - Click 'New repository secret' for each secret above"
echo ""
echo "3. Consider rotating other sensitive credentials:"
echo "   - Email SMTP password (already exposed)"
echo "   - Database passwords"
echo "   - JWT secrets"
echo ""
echo "4. NEVER commit secrets to Git!"
echo ""
echo "=================================================="

