name: CI - Build AuthService

on:
  push:
    branches:
      - main
    paths:
      - 'src/AuthService/**'
  
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::855160720656:role/GitHubActionRole-Healink # THAY BẰNG ARN CỦA BẠN
          aws-region: ap-southeast-2 # Thay bằng region của bạn

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: healink/auth-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building image for AuthService..."
          # THAY ĐỔI Ở ĐÂY: Cập nhật đường dẫn đến Dockerfile
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f src/AuthService/AuthService.API/Dockerfile .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG